//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework.domain_events._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addSavingAccountDomainEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addSavingAccountDomainEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="checkbookReferecenNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="initialFunds" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addSavingAccountDomainEvent", propOrder = {
    "checkbookReferecenNumber",
    "accountNumber",
    "initialFunds"
})
public class AddSavingAccountDomainEvent {

    @XmlElement(required = true)
    protected String checkbookReferecenNumber;
    @XmlElement(required = true)
    protected String accountNumber;
    protected double initialFunds;
    @XmlAttribute(name = "operationIdentifier")
    protected String operationIdentifier;

    /**
     * Gets the value of the checkbookReferecenNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckbookReferecenNumber() {
        return checkbookReferecenNumber;
    }

    /**
     * Sets the value of the checkbookReferecenNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckbookReferecenNumber(String value) {
        this.checkbookReferecenNumber = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the initialFunds property.
     * 
     */
    public double getInitialFunds() {
        return initialFunds;
    }

    /**
     * Sets the value of the initialFunds property.
     * 
     */
    public void setInitialFunds(double value) {
        this.initialFunds = value;
    }

    /**
     * Gets the value of the operationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationIdentifier() {
        return operationIdentifier;
    }

    /**
     * Sets the value of the operationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationIdentifier(String value) {
        this.operationIdentifier = value;
    }

}
