//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework.domain_events._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enterpriseProductsDomainEvents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enterpriseProductsDomainEvents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}addDomainEvent" minOccurs="0"/>
 *         &lt;element name="cancelDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}cancelDomainEvent" minOccurs="0"/>
 *         &lt;element name="addChekingAccountDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}addChekingAccountDomainEvent" minOccurs="0"/>
 *         &lt;element name="addSavingAccountDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}addSavingAccountDomainEvent" minOccurs="0"/>
 *         &lt;element name="addCardDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}addCardDomainEvent" minOccurs="0"/>
 *         &lt;element name="cancelCardDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}cancelCardDomainEvent" minOccurs="0"/>
 *         &lt;element name="addLoanDomainEvent" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}addLoanDomainEvent" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enterpriseProductsDomainEvents", propOrder = {
    "addDomainEvent",
    "cancelDomainEvent",
    "addChekingAccountDomainEvent",
    "addSavingAccountDomainEvent",
    "addCardDomainEvent",
    "cancelCardDomainEvent",
    "addLoanDomainEvent"
})
public class EnterpriseProductsDomainEvents {

    protected AddDomainEvent addDomainEvent;
    protected CancelDomainEvent cancelDomainEvent;
    protected AddChekingAccountDomainEvent addChekingAccountDomainEvent;
    protected AddSavingAccountDomainEvent addSavingAccountDomainEvent;
    protected AddCardDomainEvent addCardDomainEvent;
    protected CancelCardDomainEvent cancelCardDomainEvent;
    protected AddLoanDomainEvent addLoanDomainEvent;

    /**
     * Gets the value of the addDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AddDomainEvent }
     *     
     */
    public AddDomainEvent getAddDomainEvent() {
        return addDomainEvent;
    }

    /**
     * Sets the value of the addDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddDomainEvent }
     *     
     */
    public void setAddDomainEvent(AddDomainEvent value) {
        this.addDomainEvent = value;
    }

    /**
     * Gets the value of the cancelDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link CancelDomainEvent }
     *     
     */
    public CancelDomainEvent getCancelDomainEvent() {
        return cancelDomainEvent;
    }

    /**
     * Sets the value of the cancelDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelDomainEvent }
     *     
     */
    public void setCancelDomainEvent(CancelDomainEvent value) {
        this.cancelDomainEvent = value;
    }

    /**
     * Gets the value of the addChekingAccountDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AddChekingAccountDomainEvent }
     *     
     */
    public AddChekingAccountDomainEvent getAddChekingAccountDomainEvent() {
        return addChekingAccountDomainEvent;
    }

    /**
     * Sets the value of the addChekingAccountDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddChekingAccountDomainEvent }
     *     
     */
    public void setAddChekingAccountDomainEvent(AddChekingAccountDomainEvent value) {
        this.addChekingAccountDomainEvent = value;
    }

    /**
     * Gets the value of the addSavingAccountDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AddSavingAccountDomainEvent }
     *     
     */
    public AddSavingAccountDomainEvent getAddSavingAccountDomainEvent() {
        return addSavingAccountDomainEvent;
    }

    /**
     * Sets the value of the addSavingAccountDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddSavingAccountDomainEvent }
     *     
     */
    public void setAddSavingAccountDomainEvent(AddSavingAccountDomainEvent value) {
        this.addSavingAccountDomainEvent = value;
    }

    /**
     * Gets the value of the addCardDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AddCardDomainEvent }
     *     
     */
    public AddCardDomainEvent getAddCardDomainEvent() {
        return addCardDomainEvent;
    }

    /**
     * Sets the value of the addCardDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddCardDomainEvent }
     *     
     */
    public void setAddCardDomainEvent(AddCardDomainEvent value) {
        this.addCardDomainEvent = value;
    }

    /**
     * Gets the value of the cancelCardDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link CancelCardDomainEvent }
     *     
     */
    public CancelCardDomainEvent getCancelCardDomainEvent() {
        return cancelCardDomainEvent;
    }

    /**
     * Sets the value of the cancelCardDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelCardDomainEvent }
     *     
     */
    public void setCancelCardDomainEvent(CancelCardDomainEvent value) {
        this.cancelCardDomainEvent = value;
    }

    /**
     * Gets the value of the addLoanDomainEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AddLoanDomainEvent }
     *     
     */
    public AddLoanDomainEvent getAddLoanDomainEvent() {
        return addLoanDomainEvent;
    }

    /**
     * Sets the value of the addLoanDomainEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddLoanDomainEvent }
     *     
     */
    public void setAddLoanDomainEvent(AddLoanDomainEvent value) {
        this.addLoanDomainEvent = value;
    }

}
