//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework.domain_events._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import universal_bank.crm.enterprise_model.framework.common_artifacts._1_0.AccountType;


/**
 * <p>Java class for executeDomesticPaymentDomainEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="executeDomesticPaymentDomainEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cashValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="clearingHouseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetAccountType" type="{http://universal-bank/crm/enterprise-model/framework/common-artifacts/1.0.0}AccountType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeDomesticPaymentDomainEvent", propOrder = {
    "cashValue",
    "clearingHouseCode",
    "targetAccountNumber",
    "targetAccountType"
})
public class ExecuteDomesticPaymentDomainEvent {

    protected double cashValue;
    @XmlElement(required = true)
    protected String clearingHouseCode;
    @XmlElement(required = true)
    protected String targetAccountNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected AccountType targetAccountType;
    @XmlAttribute(name = "operationIdentifier")
    protected String operationIdentifier;

    /**
     * Gets the value of the cashValue property.
     * 
     */
    public double getCashValue() {
        return cashValue;
    }

    /**
     * Sets the value of the cashValue property.
     * 
     */
    public void setCashValue(double value) {
        this.cashValue = value;
    }

    /**
     * Gets the value of the clearingHouseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingHouseCode() {
        return clearingHouseCode;
    }

    /**
     * Sets the value of the clearingHouseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingHouseCode(String value) {
        this.clearingHouseCode = value;
    }

    /**
     * Gets the value of the targetAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetAccountNumber() {
        return targetAccountNumber;
    }

    /**
     * Sets the value of the targetAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetAccountNumber(String value) {
        this.targetAccountNumber = value;
    }

    /**
     * Gets the value of the targetAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getTargetAccountType() {
        return targetAccountType;
    }

    /**
     * Sets the value of the targetAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setTargetAccountType(AccountType value) {
        this.targetAccountType = value;
    }

    /**
     * Gets the value of the operationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationIdentifier() {
        return operationIdentifier;
    }

    /**
     * Sets the value of the operationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationIdentifier(String value) {
        this.operationIdentifier = value;
    }

}
