//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework.domain_events._1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the universal_bank.crm.enterprise_model.framework.domain_events._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: universal_bank.crm.enterprise_model.framework.domain_events._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExecuteElectronicPaymentDomainEvent }
     * 
     */
    public ExecuteElectronicPaymentDomainEvent createExecuteElectronicPaymentDomainEvent() {
        return new ExecuteElectronicPaymentDomainEvent();
    }

    /**
     * Create an instance of {@link ExecuteAccountToAccountPaymentDomainEvent }
     * 
     */
    public ExecuteAccountToAccountPaymentDomainEvent createExecuteAccountToAccountPaymentDomainEvent() {
        return new ExecuteAccountToAccountPaymentDomainEvent();
    }

    /**
     * Create an instance of {@link CancelCardDomainEvent }
     * 
     */
    public CancelCardDomainEvent createCancelCardDomainEvent() {
        return new CancelCardDomainEvent();
    }

    /**
     * Create an instance of {@link AddDomainEvent }
     * 
     */
    public AddDomainEvent createAddDomainEvent() {
        return new AddDomainEvent();
    }

    /**
     * Create an instance of {@link CancelDomainEvent }
     * 
     */
    public CancelDomainEvent createCancelDomainEvent() {
        return new CancelDomainEvent();
    }

    /**
     * Create an instance of {@link AddSavingAccountDomainEvent }
     * 
     */
    public AddSavingAccountDomainEvent createAddSavingAccountDomainEvent() {
        return new AddSavingAccountDomainEvent();
    }

    /**
     * Create an instance of {@link AddCardDomainEvent }
     * 
     */
    public AddCardDomainEvent createAddCardDomainEvent() {
        return new AddCardDomainEvent();
    }

    /**
     * Create an instance of {@link AddChekingAccountDomainEvent }
     * 
     */
    public AddChekingAccountDomainEvent createAddChekingAccountDomainEvent() {
        return new AddChekingAccountDomainEvent();
    }

    /**
     * Create an instance of {@link ExecuteDomesticPaymentDomainEvent }
     * 
     */
    public ExecuteDomesticPaymentDomainEvent createExecuteDomesticPaymentDomainEvent() {
        return new ExecuteDomesticPaymentDomainEvent();
    }

    /**
     * Create an instance of {@link AddCustomerDomainEvent }
     * 
     */
    public AddCustomerDomainEvent createAddCustomerDomainEvent() {
        return new AddCustomerDomainEvent();
    }

    /**
     * Create an instance of {@link EnterpriseProductsDomainEvents }
     * 
     */
    public EnterpriseProductsDomainEvents createEnterpriseProductsDomainEvents() {
        return new EnterpriseProductsDomainEvents();
    }

    /**
     * Create an instance of {@link FinancialActionDomainEvents }
     * 
     */
    public FinancialActionDomainEvents createFinancialActionDomainEvents() {
        return new FinancialActionDomainEvents();
    }

    /**
     * Create an instance of {@link EnterpriseServicesDomainEvents }
     * 
     */
    public EnterpriseServicesDomainEvents createEnterpriseServicesDomainEvents() {
        return new EnterpriseServicesDomainEvents();
    }

    /**
     * Create an instance of {@link AddLoanDomainEvent }
     * 
     */
    public AddLoanDomainEvent createAddLoanDomainEvent() {
        return new AddLoanDomainEvent();
    }

}
