//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import universal_bank.crm.enterprise_model.framework.common_artifacts._1_0.BusinessEventType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventHeader" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}eventHeader"/>
 *         &lt;element name="businessEventType" type="{http://universal-bank/crm/enterprise-model/framework/common-artifacts/1.0.0}BusinessEventType"/>
 *         &lt;element name="enterpriseOperationEventObject" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}enterpriseOperationEventObject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventHeader",
    "businessEventType",
    "enterpriseOperationEventObject"
})
@XmlRootElement(name = "CRMBusinessEvent")
public class CRMBusinessEvent {

    @XmlElement(required = true)
    protected EventHeader eventHeader;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BusinessEventType businessEventType;
    @XmlElement(required = true)
    protected EnterpriseOperationEventObject enterpriseOperationEventObject;

    /**
     * Gets the value of the eventHeader property.
     * 
     * @return
     *     possible object is
     *     {@link EventHeader }
     *     
     */
    public EventHeader getEventHeader() {
        return eventHeader;
    }

    /**
     * Sets the value of the eventHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventHeader }
     *     
     */
    public void setEventHeader(EventHeader value) {
        this.eventHeader = value;
    }

    /**
     * Gets the value of the businessEventType property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessEventType }
     *     
     */
    public BusinessEventType getBusinessEventType() {
        return businessEventType;
    }

    /**
     * Sets the value of the businessEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessEventType }
     *     
     */
    public void setBusinessEventType(BusinessEventType value) {
        this.businessEventType = value;
    }

    /**
     * Gets the value of the enterpriseOperationEventObject property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseOperationEventObject }
     *     
     */
    public EnterpriseOperationEventObject getEnterpriseOperationEventObject() {
        return enterpriseOperationEventObject;
    }

    /**
     * Sets the value of the enterpriseOperationEventObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseOperationEventObject }
     *     
     */
    public void setEnterpriseOperationEventObject(EnterpriseOperationEventObject value) {
        this.enterpriseOperationEventObject = value;
    }

}
