//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enterpriseOperationEventObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enterpriseOperationEventObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="branchOfficeInfo" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}branchOfficeInfo"/>
 *         &lt;element name="customerInfo" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}customerInfo"/>
 *         &lt;element name="financialActionDomainObject" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}financialActionDomainObject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="enterpriseOperationKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enterpriseOperationEventObject", propOrder = {
    "branchOfficeInfo",
    "customerInfo",
    "financialActionDomainObject"
})
public class EnterpriseOperationEventObject {

    @XmlElement(required = true)
    protected BranchOfficeInfo branchOfficeInfo;
    @XmlElement(required = true)
    protected CustomerInfo customerInfo;
    @XmlElement(required = true)
    protected List<FinancialActionDomainObject> financialActionDomainObject;
    @XmlAttribute(name = "enterpriseOperationKey")
    protected String enterpriseOperationKey;

    /**
     * Gets the value of the branchOfficeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BranchOfficeInfo }
     *     
     */
    public BranchOfficeInfo getBranchOfficeInfo() {
        return branchOfficeInfo;
    }

    /**
     * Sets the value of the branchOfficeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchOfficeInfo }
     *     
     */
    public void setBranchOfficeInfo(BranchOfficeInfo value) {
        this.branchOfficeInfo = value;
    }

    /**
     * Gets the value of the customerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerInfo }
     *     
     */
    public CustomerInfo getCustomerInfo() {
        return customerInfo;
    }

    /**
     * Sets the value of the customerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerInfo }
     *     
     */
    public void setCustomerInfo(CustomerInfo value) {
        this.customerInfo = value;
    }

    /**
     * Gets the value of the financialActionDomainObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the financialActionDomainObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinancialActionDomainObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialActionDomainObject }
     * 
     * 
     */
    public List<FinancialActionDomainObject> getFinancialActionDomainObject() {
        if (financialActionDomainObject == null) {
            financialActionDomainObject = new ArrayList<FinancialActionDomainObject>();
        }
        return this.financialActionDomainObject;
    }

    /**
     * Gets the value of the enterpriseOperationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseOperationKey() {
        return enterpriseOperationKey;
    }

    /**
     * Sets the value of the enterpriseOperationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseOperationKey(String value) {
        this.enterpriseOperationKey = value;
    }

}
