//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import universal_bank.crm.enterprise_model.framework.common_artifacts._1_0.ServiceType;
import universal_bank.crm.enterprise_model.framework.domain_events._1_0.EnterpriseServicesDomainEvents;


/**
 * <p>Java class for financialService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="financialService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://universal-bank/crm/enterprise-model/framework/common-artifacts/1.0.0}ServiceType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceScheduledInfo" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}serviceScheduledInfo"/>
 *         &lt;element name="enterpriseServicesDomainEvents" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}enterpriseServicesDomainEvents"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "financialService", propOrder = {
    "type",
    "description",
    "serviceScheduledInfo",
    "enterpriseServicesDomainEvents"
})
public class FinancialService {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ServiceType type;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected ServiceScheduledInfo serviceScheduledInfo;
    @XmlElement(required = true)
    protected EnterpriseServicesDomainEvents enterpriseServicesDomainEvents;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setType(ServiceType value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the serviceScheduledInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceScheduledInfo }
     *     
     */
    public ServiceScheduledInfo getServiceScheduledInfo() {
        return serviceScheduledInfo;
    }

    /**
     * Sets the value of the serviceScheduledInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceScheduledInfo }
     *     
     */
    public void setServiceScheduledInfo(ServiceScheduledInfo value) {
        this.serviceScheduledInfo = value;
    }

    /**
     * Gets the value of the enterpriseServicesDomainEvents property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseServicesDomainEvents }
     *     
     */
    public EnterpriseServicesDomainEvents getEnterpriseServicesDomainEvents() {
        return enterpriseServicesDomainEvents;
    }

    /**
     * Sets the value of the enterpriseServicesDomainEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseServicesDomainEvents }
     *     
     */
    public void setEnterpriseServicesDomainEvents(EnterpriseServicesDomainEvents value) {
        this.enterpriseServicesDomainEvents = value;
    }

}
