//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import universal_bank.crm.enterprise_model.framework.common_artifacts._1_0.ProductType;
import universal_bank.crm.enterprise_model.framework.domain_events._1_0.EnterpriseProductsDomainEvents;


/**
 * <p>Java class for financialProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="financialProduct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://universal-bank/crm/enterprise-model/framework/common-artifacts/1.0.0}ProductType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referenceCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="enterpriseProductsDomainEvents" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}enterpriseProductsDomainEvents"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "financialProduct", propOrder = {
    "type",
    "description",
    "serialNumber",
    "referenceCost",
    "enterpriseProductsDomainEvents"
})
public class FinancialProduct {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ProductType type;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String serialNumber;
    protected double referenceCost;
    @XmlElement(required = true)
    protected EnterpriseProductsDomainEvents enterpriseProductsDomainEvents;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setType(ProductType value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the referenceCost property.
     * 
     */
    public double getReferenceCost() {
        return referenceCost;
    }

    /**
     * Sets the value of the referenceCost property.
     * 
     */
    public void setReferenceCost(double value) {
        this.referenceCost = value;
    }

    /**
     * Gets the value of the enterpriseProductsDomainEvents property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseProductsDomainEvents }
     *     
     */
    public EnterpriseProductsDomainEvents getEnterpriseProductsDomainEvents() {
        return enterpriseProductsDomainEvents;
    }

    /**
     * Sets the value of the enterpriseProductsDomainEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseProductsDomainEvents }
     *     
     */
    public void setEnterpriseProductsDomainEvents(EnterpriseProductsDomainEvents value) {
        this.enterpriseProductsDomainEvents = value;
    }

}
