//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import universal_bank.crm.enterprise_model.framework.domain_events._1_0.FinancialActionDomainEvents;


/**
 * <p>Java class for financialActionDomainObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="financialActionDomainObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="financialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="financialProduct" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}financialProduct" minOccurs="0"/>
 *         &lt;element name="financialService" type="{http://universal-bank/crm/enterprise-model/framework/1.0.0}financialService" minOccurs="0"/>
 *         &lt;element name="taxes" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="operationCost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="financialActionDomainEvents" type="{http://universal-bank/crm/enterprise-model/framework/domain-events/1.0.0}financialActionDomainEvents"/>
 *       &lt;/sequence>
 *       &lt;attribute name="externalKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "financialActionDomainObject", propOrder = {
    "sequenceNumber",
    "financialNumber",
    "description",
    "financialProduct",
    "financialService",
    "taxes",
    "operationCost",
    "financialActionDomainEvents"
})
public class FinancialActionDomainObject {

    @XmlElement(required = true)
    protected String sequenceNumber;
    @XmlElement(required = true)
    protected String financialNumber;
    @XmlElement(required = true)
    protected String description;
    protected FinancialProduct financialProduct;
    protected FinancialService financialService;
    protected double taxes;
    protected double operationCost;
    @XmlElement(required = true)
    protected FinancialActionDomainEvents financialActionDomainEvents;
    @XmlAttribute(name = "externalKey")
    protected String externalKey;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the financialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialNumber() {
        return financialNumber;
    }

    /**
     * Sets the value of the financialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialNumber(String value) {
        this.financialNumber = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the financialProduct property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialProduct }
     *     
     */
    public FinancialProduct getFinancialProduct() {
        return financialProduct;
    }

    /**
     * Sets the value of the financialProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialProduct }
     *     
     */
    public void setFinancialProduct(FinancialProduct value) {
        this.financialProduct = value;
    }

    /**
     * Gets the value of the financialService property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialService }
     *     
     */
    public FinancialService getFinancialService() {
        return financialService;
    }

    /**
     * Sets the value of the financialService property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialService }
     *     
     */
    public void setFinancialService(FinancialService value) {
        this.financialService = value;
    }

    /**
     * Gets the value of the taxes property.
     * 
     */
    public double getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     * 
     */
    public void setTaxes(double value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the operationCost property.
     * 
     */
    public double getOperationCost() {
        return operationCost;
    }

    /**
     * Sets the value of the operationCost property.
     * 
     */
    public void setOperationCost(double value) {
        this.operationCost = value;
    }

    /**
     * Gets the value of the financialActionDomainEvents property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialActionDomainEvents }
     *     
     */
    public FinancialActionDomainEvents getFinancialActionDomainEvents() {
        return financialActionDomainEvents;
    }

    /**
     * Sets the value of the financialActionDomainEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialActionDomainEvents }
     *     
     */
    public void setFinancialActionDomainEvents(FinancialActionDomainEvents value) {
        this.financialActionDomainEvents = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

}
