//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 06:24:47 PM EDT 
//


package universal_bank.crm.enterprise_model.framework._1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the universal_bank.crm.enterprise_model.framework._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: universal_bank.crm.enterprise_model.framework._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CRMBusinessEvent }
     * 
     */
    public CRMBusinessEvent createCRMBusinessEvent() {
        return new CRMBusinessEvent();
    }

    /**
     * Create an instance of {@link EventHeader }
     * 
     */
    public EventHeader createEventHeader() {
        return new EventHeader();
    }

    /**
     * Create an instance of {@link EnterpriseOperationEventObject }
     * 
     */
    public EnterpriseOperationEventObject createEnterpriseOperationEventObject() {
        return new EnterpriseOperationEventObject();
    }

    /**
     * Create an instance of {@link FinancialActionDomainObject }
     * 
     */
    public FinancialActionDomainObject createFinancialActionDomainObject() {
        return new FinancialActionDomainObject();
    }

    /**
     * Create an instance of {@link FinancialService }
     * 
     */
    public FinancialService createFinancialService() {
        return new FinancialService();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link ServiceScheduledInfo }
     * 
     */
    public ServiceScheduledInfo createServiceScheduledInfo() {
        return new ServiceScheduledInfo();
    }

    /**
     * Create an instance of {@link BranchOfficeInfo }
     * 
     */
    public BranchOfficeInfo createBranchOfficeInfo() {
        return new BranchOfficeInfo();
    }

    /**
     * Create an instance of {@link CustomerInfo }
     * 
     */
    public CustomerInfo createCustomerInfo() {
        return new CustomerInfo();
    }

    /**
     * Create an instance of {@link FinancialProduct }
     * 
     */
    public FinancialProduct createFinancialProduct() {
        return new FinancialProduct();
    }

}
